<?php

require_once __DIR__ . '/config/db.php';

function initializeDatabase(PDO $pdo): void
{
    $pdo->exec("DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'drop_status') THEN
            CREATE TYPE drop_status AS ENUM ('upcoming','live','sold_out','ended');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'listing_status') THEN
            CREATE TYPE listing_status AS ENUM ('active','sold','removed');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'watch_status') THEN
            CREATE TYPE watch_status AS ENUM ('active','paused','triggered');
        END IF;
    END$$;");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS drops (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            brand VARCHAR(100) NOT NULL,
            model VARCHAR(150),
            sku VARCHAR(100),
            colorway VARCHAR(150),
            release_date TIMESTAMP NOT NULL,
            retail_price NUMERIC(10,2) NOT NULL,
            currency VARCHAR(10) DEFAULT 'EUR',
            image_url TEXT,
            store_name VARCHAR(100),
            store_link TEXT,
            description TEXT,
            status drop_status DEFAULT 'upcoming',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            ai_summary TEXT
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(100) NOT NULL,
            email VARCHAR(150) NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            role VARCHAR(255),
            is_verified BOOLEAN NOT NULL DEFAULT FALSE,
            verify_token VARCHAR(255),
            verification_expires_at TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS favorites (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            drop_id INTEGER NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS listings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            drop_id INTEGER NOT NULL,
            price NUMERIC(10,2) NOT NULL,
            size VARCHAR(20) NOT NULL,
            condition_note VARCHAR(255),
            status listing_status DEFAULT 'active',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS price_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            drop_id INTEGER NOT NULL,
            market_price NUMERIC(10,2) NOT NULL,
            recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS price_watchlist (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            discord_user_id VARCHAR(50) NOT NULL,
            product_url TEXT NOT NULL,
            product_title VARCHAR(255),
            current_price NUMERIC(10,2),
            source_price NUMERIC(12,2),
            target_price NUMERIC(10,2) NOT NULL,
            currency VARCHAR(10) DEFAULT 'CZK',
            source_currency VARCHAR(8),
            last_checked_at TIMESTAMP,
            last_notified_price NUMERIC(10,2),
            status watch_status DEFAULT 'active',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS price_watch_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            watch_id INTEGER NOT NULL,
            checked_price NUMERIC(10,2),
            in_stock BOOLEAN DEFAULT TRUE,
            checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS resell_stats (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            drop_id INTEGER NOT NULL,
            avg_resell_price NUMERIC(10,2),
            min_resell_price NUMERIC(10,2),
            max_resell_price NUMERIC(10,2),
            demand_score INTEGER,
            resell_score INTEGER,
            source VARCHAR(100),
            checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");
}

function seedDatabase(PDO $pdo): void
{
    $dropCount = (int)$pdo->query("SELECT COUNT(*) FROM drops")->fetchColumn();

    if ($dropCount === 0) {
        $stmt = $pdo->prepare("
            INSERT INTO drops (
                id, title, brand, model, sku, colorway, release_date,
                retail_price, currency, image_url, store_name, store_link,
                description, status, created_at, updated_at, ai_summary
            ) VALUES (
                :id, :title, :brand, :model, :sku, :colorway, :release_date,
                :retail_price, :currency, :image_url, :store_name, :store_link,
                :description, :status, :created_at, :updated_at, :ai_summary
            )
            ON CONFLICT (id) DO NOTHING
        ");

        $stmt->execute([
            ':id' => 1,
            ':title' => 'Nike Dunk Low Panda',
            ':brand' => 'Nike',
            ':model' => 'Dunk Low',
            ':sku' => 'DD1391-100',
            ':colorway' => 'Black / White',
            ':release_date' => '2026-04-10 09:00:00',
            ':retail_price' => 120.00,
            ':currency' => 'EUR',
            ':image_url' => 'https://static.ftshp.digital/img/p/6/7/4/9/7/1/674971-full_product.jpg',
            ':store_name' => 'Nike SNKRS',
            ':store_link' => 'https://example.com/drop-link',
            ':description' => 'Populární model s vysokou poptávkou.',
            ':status' => 'upcoming',
            ':created_at' => '2026-03-25 22:40:08',
            ':updated_at' => '2026-04-08 22:49:42',
            ':ai_summary' => 'Nike Dunk Low Panda je populární model z řady Dunk Low s klasickou černo-bílou kombinací. Působí jako bezpečný mainstream pick pro běžné nošení i sledování zájmu po releasu. Nejde o extrémně odvážný kus, ale díky známému vzhledu může být pro řadu lidí zajímavý.'
        ]);

        $stmt->execute([
            ':id' => 2,
            ':title' => 'Air Jordan 1 Retro High OG',
            ':brand' => 'Jordan',
            ':model' => 'Jordan 1 High',
            ':sku' => 'DZ5485-010',
            ':colorway' => 'Black / Red',
            ':release_date' => '2026-04-14 09:00:00',
            ':retail_price' => 190.00,
            ':currency' => 'EUR',
            ':image_url' => 'https://blob.sxv.pl/shops/media/f1000/2023/nike/221577/air-jordan-1-retro-high-og-dz5485-042-653f88e9c297e.jpg',
            ':store_name' => 'Nike SNKRS',
            ':store_link' => 'https://example.com/jordan-drop',
            ':description' => 'Velmi očekávaný release.',
            ':status' => 'upcoming',
            ':created_at' => '2026-03-25 22:40:08',
            ':updated_at' => '2026-03-25 22:44:28',
            ':ai_summary' => 'Air Jordan 1 Retro High OG působí jako silnější a výraznější release než běžné mainstream modely. Díky známé siluetě a tradičně vysokému zájmu o Jordan 1 může být zajímavý jak pro fanoušky značky, tak pro sledování resale potenciálu. Zároveň ale bude hodně záležet na reálné poptávce po vydání.'
        ]);
    }
}

initializeDatabase($pdo);
seedDatabase($pdo);
