<?php

require_once __DIR__ . '/config/db.php';

function tableExists(PDO $pdo, string $tableName): bool
{
    $stmt = $pdo->prepare("
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = :table_name
        )
    ");
    $stmt->execute([':table_name' => $tableName]);
    return (bool) $stmt->fetchColumn();
}

function initializeDatabase(PDO $pdo): void
{
    $pdo->exec("DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'drop_status') THEN
            CREATE TYPE drop_status AS ENUM ('upcoming','live','sold_out','ended');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'listing_status') THEN
            CREATE TYPE listing_status AS ENUM ('active','sold','removed');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'watch_status') THEN
            CREATE TYPE watch_status AS ENUM ('active','paused','triggered');
        END IF;
    END$$;");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS drops (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title varchar(255) NOT NULL,
            brand varchar(100) NOT NULL,
            model varchar(150),
            sku varchar(100),
            colorway varchar(150),
            release_date timestamp NOT NULL,
            retail_price numeric(10,2) NOT NULL,
            currency varchar(10) DEFAULT 'EUR',
            image_url text,
            store_name varchar(100),
            store_link text,
            description text,
            status drop_status DEFAULT 'upcoming',
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            ai_summary text
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS users (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username varchar(100) NOT NULL,
            email varchar(150) NOT NULL,
            password_hash varchar(255) NOT NULL,
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
            role varchar(255),
            is_verified boolean NOT NULL DEFAULT FALSE,
            verify_token varchar(255),
            verification_expires_at timestamp
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS favorites (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id integer NOT NULL,
            drop_id integer NOT NULL,
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS listings (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id integer NOT NULL,
            drop_id integer NOT NULL,
            price numeric(10,2) NOT NULL,
            size varchar(20) NOT NULL,
            condition_note varchar(255),
            status listing_status DEFAULT 'active',
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS price_history (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            drop_id integer NOT NULL,
            market_price numeric(10,2) NOT NULL,
            recorded_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS price_watchlist (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            discord_user_id varchar(50) NOT NULL,
            product_url text NOT NULL,
            product_title varchar(255),
            current_price numeric(10,2),
            source_price numeric(12,2),
            target_price numeric(10,2) NOT NULL,
            currency varchar(10) DEFAULT 'CZK',
            source_currency varchar(8),
            last_checked_at timestamp,
            last_notified_price numeric(10,2),
            status watch_status DEFAULT 'active',
            created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS price_watch_history (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            watch_id integer NOT NULL,
            checked_price numeric(10,2),
            in_stock boolean DEFAULT TRUE,
            checked_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS resell_stats (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            drop_id integer NOT NULL,
            avg_resell_price numeric(10,2),
            min_resell_price numeric(10,2),
            max_resell_price numeric(10,2),
            demand_score integer,
            resell_score integer,
            source varchar(100),
            checked_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");
}

function seedDatabase(PDO $pdo): void
{
    $dropCount = (int)$pdo->query("SELECT COUNT(*) FROM drops")->fetchColumn();
    if ($dropCount === 0) {
        $stmt = $pdo->prepare("
            INSERT INTO drops (
                id, title, brand, model, sku, colorway, release_date,
                retail_price, currency, image_url, store_name, store_link,
                description, status, created_at, updated_at, ai_summary
            ) VALUES (
                :id, :title, :brand, :model, :sku, :colorway, :release_date,
                :retail_price, :currency, :image_url, :store_name, :store_link,
                :description, :status, :created_at, :updated_at, :ai_summary
            )
            ON CONFLICT (id) DO NOTHING
        ");

        $stmt->execute([
            ':id' => 1,
            ':title' => 'Nike Dunk Low Panda',
            ':brand' => 'Nike',
            ':model' => 'Dunk Low',
            ':sku' => 'DD1391-100',
            ':colorway' => 'Black / White',
            ':release_date' => '2026-04-10 09:00:00',
            ':retail_price' => 120.00,
            ':currency' => 'EUR',
            ':image_url' => 'https://static.ftshp.digital/img/p/6/7/4/9/7/1/674971-full_product.jpg',
            ':store_name' => 'Nike SNKRS',
            ':store_link' => 'https://example.com/drop-link',
            ':description' => 'Populární model s vysokou poptávkou.',
            ':status' => 'upcoming',
            ':created_at' => '2026-03-25 22:40:08',
            ':updated_at' => '2026-04-08 22:49:42',
            ':ai_summary' => 'Nike Dunk Low Panda je nový, populární model z řady Dunk Low. Tento drop se vyrábí v tmavě šedé a bílé barvě, což je oblíbená kombinace. Je to model, který se pravděpodobně bude hodit pro milovníky ikonických sneaker modelů.'
        ]);

        $stmt->execute([
            ':id' => 2,
            ':title' => 'Air Jordan 1 Retro High OG',
            ':brand' => 'Jordan',
            ':model' => 'Jordan 1 High',
            ':sku' => 'DZ5485-010',
            ':colorway' => 'Black / Red',
            ':release_date' => '2026-04-14 09:00:00',
            ':retail_price' => 190.00,
            ':currency' => 'EUR',
            ':image_url' => 'https://blob.sxv.pl/shops/media/f1000/2023/nike/221577/air-jordan-1-retro-high-og-dz5485-042-653f88e9c297e.jpg',
            ':store_name' => 'Nike SNKRS',
            ':store_link' => 'https://example.com/jordan-drop',
            ':description' => 'Velmi očekávaný release.',
            ':status' => 'upcoming',
            ':created_at' => '2026-03-25 22:40:08',
            ':updated_at' => '2026-03-25 22:44:28',
            ':ai_summary' => null
        ]);
    }

    $userCount = (int)$pdo->query("SELECT COUNT(*) FROM users")->fetchColumn();
    if ($userCount === 0) {
        $stmt = $pdo->prepare("
            INSERT INTO users (
                id, username, email, password_hash, created_at, role,
                is_verified, verify_token, verification_expires_at
            ) VALUES (
                :id, :username, :email, :password_hash, :created_at, :role,
                :is_verified, :verify_token, :verification_expires_at
            )
            ON CONFLICT (id) DO NOTHING
        ");

        $stmt->execute([
            ':id' => 1,
            ':username' => 'dannyz',
            ':email' => 'danielzoubek97@gmail.com',
            ':password_hash' => '$2y$12$tRjjBUWdlxQNuQZIPbfIjOKZ0CSo8djWnrnz.ENTBgs/hpcK58RwS',
            ':created_at' => '2026-03-26 22:28:09',
            ':role' => null,
            ':is_verified' => false,
            ':verify_token' => null,
            ':verification_expires_at' => null
        ]);

        $stmt->execute([
            ':id' => 6,
            ':username' => 'furgalof',
            ':email' => 'denis.portal.de@gmail.com',
            ':password_hash' => '$2y$12$CfYvfBR5X95ZNnEO3Vo8.elNYGjKjPNAXHnX9QJJvnDGrGpTSfSxW',
            ':created_at' => '2026-03-30 22:01:52',
            ':role' => null,
            ':is_verified' => true,
            ':verify_token' => null,
            ':verification_expires_at' => null
        ]);
    }

    $watchCount = (int)$pdo->query("SELECT COUNT(*) FROM price_watchlist")->fetchColumn();
    if ($watchCount === 0) {
        $stmt = $pdo->prepare("
            INSERT INTO price_watchlist (
                id, discord_user_id, product_url, product_title, current_price,
                source_price, target_price, currency, source_currency,
                last_checked_at, last_notified_price, status, created_at
            ) VALUES (
                :id, :discord_user_id, :product_url, :product_title, :current_price,
                :source_price, :target_price, :currency, :source_currency,
                :last_checked_at, :last_notified_price, :status, :created_at
            )
            ON CONFLICT (id) DO NOTHING
        ");

        $rows = [
            [4, '376394315234017302', 'https://www.alza.cz/gaming/thrustmaster-t128-ps-d7455551.htm', 'Volant Thrustmaster T128 PS', 4649.00, 4579.00, 3800.00, 'CZK', 'CZK', '2026-04-16 06:52:41', 3790.00, 'active', '2026-03-29 21:31:37'],
            [5, '376394315234017302', 'https://www.alza.cz/gaming/thrustmaster-t128-ps-d7455551.htm', 'Volant Thrustmaster T128 PS', 4649.00, 4579.00, 3800.00, 'CZK', 'CZK', '2026-04-16 06:52:41', 3790.00, 'active', '2026-03-29 21:42:01'],
            [6, '376394315234017302', 'https://www.sephora.cz/p/natural-matte-longwear-foundation---matny-dlouhotrvajici-make-up-P1000212528.html', 'Access Denied', null, 1490.00, 1500.00, 'CZK', 'CZK', '2026-04-16 06:52:45', null, 'active', '2026-03-30 19:46:15'],
            [11, '376394315234017302', 'https://euqs.shein.com/Zrgoth-Men-s-Casual-Versatile-Rose-Flower-Print-Short-Sleeve-T-Shirt-p-354644936.html?&mall_code=1', 'Dámské a pánské oblečení, módní nákupy online | SHEIN', null, 1.00, 5.00, 'CZK', 'USD', '2026-04-16 06:52:51', 1.00, 'active', '2026-04-08 20:06:49'],
            [12, '376394315234017302', 'https://www.amazon.com/Concept-Compatible-Polarizer-Neutral-Accessories/dp/B0DJR24JGT/ref=sr_1_4?dib=eyJ2IjoiMSJ9.Ag5w1fuWqrkaUfryNgPae2FISH-mobV1gO23GTsEtWmcFenVBAuV-VWDgqFkF8KCWo0MlkTfrfeJUiYLD4YPAm55JI9Bm9yYluTAWUHYJR5iOKOcAMsd_JtX1fzgZ5ndALZIxOJEXm-gVVMBvvW6XRsUlpYJvm2yOhUzVd2P4iCdWVck6Xzxz1hGhrB3Vsf6IG3So-ZtP6EeblYvGbp4tLZbEg50NFte6Y-XVvZHHuY.ADajiRR4rxJfANk0isLRn6TikwroNwqDkULNz1p_HpE&dib_tag=se&keywords=k%26f%2Bconcept%2Bnd%2Bfilter%2BOsmo%2BACtion%2B5%2Bpro&qid=1775684349&sr=8-4&th=1', 'Amazon.com : K&F CONCEPT ND Filter Compatible with DJI Osmo Action 5 Pro/Osmo Action 4, 6 Pack CPL ND8 ND16 ND32 ND64 ND256 Polarizer Neutral Density Filter Action Camera Accessories, Multi Coated HD Optical Glass : Electronics', 825.87, null, 900.00, 'CZK', null, '2026-04-16 06:52:53', 824.71, 'active', '2026-04-08 21:39:48'],
            [13, '311576597310341120', 'https://www.sephora.cz/p/natural-matte-longwear-foundation---matny-dlouhotrvajici-make-up-P1000212528.html', 'Access Denied', null, null, 1600.00, 'CZK', null, '2026-04-16 06:52:45', null, 'active', '2026-04-09 05:11:05'],
        ];

        foreach ($rows as $row) {
            $stmt->execute([
                ':id' => $row[0],
                ':discord_user_id' => $row[1],
                ':product_url' => $row[2],
                ':product_title' => $row[3],
                ':current_price' => $row[4],
                ':source_price' => $row[5],
                ':target_price' => $row[6],
                ':currency' => $row[7],
                ':source_currency' => $row[8],
                ':last_checked_at' => $row[9],
                ':last_notified_price' => $row[10],
                ':status' => $row[11],
                ':created_at' => $row[12],
            ]);
        }
    }

    $historyCount = (int)$pdo->query("SELECT COUNT(*) FROM price_watch_history")->fetchColumn();
    if ($historyCount === 0) {
        $stmt = $pdo->prepare("
            INSERT INTO price_watch_history (
                id, watch_id, checked_price, in_stock, checked_at
            ) VALUES (
                :id, :watch_id, :checked_price, :in_stock, :checked_at
            )
            ON CONFLICT (id) DO NOTHING
        ");

        $historyRows = [
            [46, 4, 3790.00, true, '2026-03-29 21:31:37'],
            [47, 4, 3790.00, true, '2026-03-29 21:31:49'],
            [48, 4, 3790.00, true, '2026-03-29 21:40:04'],
            [49, 4, 3790.00, true, '2026-03-29 21:41:22'],
            [50, 5, 3790.00, true, '2026-03-29 21:42:01'],
            [51, 5, 3790.00, true, '2026-03-29 21:42:13'],
            [52, 4, 4579.00, true, '2026-03-29 23:40:13'],
            [53, 5, 4579.00, true, '2026-03-29 23:40:13'],
            [54, 4, 4579.00, true, '2026-03-30 01:40:20'],
            [55, 5, 4579.00, true, '2026-03-30 01:40:20']
        ];

        foreach ($historyRows as $row) {
            $stmt->execute([
                ':id' => $row[0],
                ':watch_id' => $row[1],
                ':checked_price' => $row[2],
                ':in_stock' => $row[3],
                ':checked_at' => $row[4],
            ]);
        }
    }
}

initializeDatabase($pdo);
seedDatabase($pdo);
