services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dropshipping_app
      DB_USER: ddrop_user
      DB_PASS: ddrop_password
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dropshipping_app
      POSTGRES_USER: ddrop_user
      POSTGRES_PASSWORD: ddrop_password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./dropshipping_app_postgres.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pg_data:
