services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dropshipping_app
      DB_USER: ddrop_user
      DB_PASS: ddrop_password
      OLD_DB_HOST: tvoje-stara-db-host
      OLD_DB_PORT: 3306
      OLD_DB_NAME: dropshipping_app
      OLD_DB_USER: tvuj_stary_user
      OLD_DB_PASS: tvoje_stare_heslo
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dropshipping_app
      POSTGRES_USER: ddrop_user
      POSTGRES_PASSWORD: ddrop_password
