<?php

$host = getenv('DB_HOST') ?: 'db';
$port = getenv('DB_PORT') ?: '5432';
$dbname = getenv('DB_NAME') ?: 'dropshipping_app';
$user = getenv('DB_USER') ?: 'ddrop_user';
$pass = getenv('DB_PASS') ?: 'ddrop_demo_password';

$pdo = null;
$lastError = null;

for ($i = 0; $i < 10; $i++) {
    try {
        $pdo = new PDO(
            "pgsql:host={$host};port={$port};dbname={$dbname}",
            $user,
            $pass,
            [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]
        );

        break;
    } catch (PDOException $e) {
        $lastError = $e;
        sleep(2);
    }
}

if (!$pdo) {
    die('DB connection failed: ' . $lastError->getMessage());
}

function ddrop_init_database(PDO $pdo): void
{
    $pdo->exec("
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_type
                WHERE typname = 'drop_status'
            ) THEN
                CREATE TYPE drop_status AS ENUM (
                    'upcoming',
                    'live',
                    'sold_out',
                    'ended'
                );
            END IF;
        END
        $$;
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(80) NOT NULL,
            email VARCHAR(160) NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS drops (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            brand VARCHAR(100) NOT NULL,
            model VARCHAR(150),
            sku VARCHAR(100),
            colorway VARCHAR(150),
            release_date TIMESTAMP NOT NULL,
            retail_price NUMERIC(10,2) NOT NULL,
            currency VARCHAR(10) DEFAULT 'EUR',
            image_url TEXT,
            store_name VARCHAR(100),
            store_link TEXT,
            description TEXT,
            status drop_status DEFAULT 'upcoming',
            ai_summary TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS watchlist (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            drop_id INTEGER NOT NULL REFERENCES drops(id) ON DELETE CASCADE,
            target_price NUMERIC(10,2) NOT NULL,
            currency VARCHAR(10) DEFAULT 'EUR',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (user_id, drop_id)
        );
    ");

    /*
        Pokud už existovala starší verze watchlist tabulky bez target_price,
        tyhle ALTERy ji bezpečně doplní.
    */
    $pdo->exec("
        ALTER TABLE watchlist
        ADD COLUMN IF NOT EXISTS target_price NUMERIC(10,2);
    ");

    $pdo->exec("
        ALTER TABLE watchlist
        ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'EUR';
    ");

    $pdo->exec("
        ALTER TABLE watchlist
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS ai_generations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            drop_id INTEGER NOT NULL REFERENCES drops(id) ON DELETE CASCADE,
            prompt TEXT NOT NULL,
            response TEXT,
            model VARCHAR(120),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ");
}

function ddrop_seed_database(PDO $pdo): void
{
    $userCount = (int)$pdo->query("SELECT COUNT(*) FROM users")->fetchColumn();

    if ($userCount === 0) {
        $stmt = $pdo->prepare("
            INSERT INTO users (
                id,
                username,
                email,
                password_hash
            ) VALUES (
                :id,
                :username,
                :email,
                :password_hash
            )
            ON CONFLICT (id) DO NOTHING
        ");

        $stmt->execute([
            ':id' => 1,
            ':username' => 'demo_user',
            ':email' => 'demo@example.test',
            ':password_hash' => password_hash('demo123', PASSWORD_DEFAULT),
        ]);
    }

    $dropCount = (int)$pdo->query("SELECT COUNT(*) FROM drops")->fetchColumn();

    if ($dropCount === 0) {
        $stmt = $pdo->prepare("
            INSERT INTO drops (
                id,
                title,
                brand,
                model,
                sku,
                colorway,
                release_date,
                retail_price,
                currency,
                image_url,
                store_name,
                store_link,
                description,
                status,
                ai_summary,
                created_at,
                updated_at
            ) VALUES (
                :id,
                :title,
                :brand,
                :model,
                :sku,
                :colorway,
                :release_date,
                :retail_price,
                :currency,
                :image_url,
                :store_name,
                :store_link,
                :description,
                :status,
                :ai_summary,
                :created_at,
                :updated_at
            )
            ON CONFLICT (id) DO NOTHING
        ");

        $drops = [
            [
                'id' => 1,
                'title' => 'Nike Dunk Low Panda',
                'brand' => 'Nike',
                'model' => 'Dunk Low',
                'sku' => 'DD1391-100',
                'colorway' => 'Black / White',
                'release_date' => '2026-04-10 09:00:00',
                'retail_price' => 120.00,
                'currency' => 'EUR',
                'image_url' => 'https://static.ftshp.digital/img/p/6/7/4/9/7/1/674971-full_product.jpg',
                'store_name' => 'Nike SNKRS',
                'store_link' => 'https://example.com/drop-link',
                'description' => 'Populární model s vysokou poptávkou.',
                'status' => 'upcoming',
                'ai_summary' => null,
                'created_at' => '2026-03-25 22:40:08',
                'updated_at' => '2026-04-08 22:49:42',
            ],
            [
                'id' => 2,
                'title' => 'Air Jordan 1 Retro High OG',
                'brand' => 'Jordan',
                'model' => 'Jordan 1 High',
                'sku' => 'DZ5485-010',
                'colorway' => 'Black / Royal Blue',
                'release_date' => '2026-04-14 09:00:00',
                'retail_price' => 190.00,
                'currency' => 'EUR',
                'image_url' => 'https://blob.sxv.pl/shops/media/f1000/2023/nike/221577/air-jordan-1-retro-high-og-dz5485-042-653f88e9c297e.jpg',
                'store_name' => 'Nike SNKRS',
                'store_link' => 'https://example.com/jordan-drop',
                'description' => 'Velmi očekávaný release.',
                'status' => 'upcoming',
                'ai_summary' => null,
                'created_at' => '2026-03-25 22:40:08',
                'updated_at' => '2026-03-25 22:44:28',
            ],
        ];

        foreach ($drops as $drop) {
            $stmt->execute([
                ':id' => $drop['id'],
                ':title' => $drop['title'],
                ':brand' => $drop['brand'],
                ':model' => $drop['model'],
                ':sku' => $drop['sku'],
                ':colorway' => $drop['colorway'],
                ':release_date' => $drop['release_date'],
                ':retail_price' => $drop['retail_price'],
                ':currency' => $drop['currency'],
                ':image_url' => $drop['image_url'],
                ':store_name' => $drop['store_name'],
                ':store_link' => $drop['store_link'],
                ':description' => $drop['description'],
                ':status' => $drop['status'],
                ':ai_summary' => $drop['ai_summary'],
                ':created_at' => $drop['created_at'],
                ':updated_at' => $drop['updated_at'],
            ]);
        }
    }

    /*
        Watchlist se záměrně neseeduje.
        Uživatel si musí cílovou cenu nastavit sám v detailu dropu.
    */

    $pdo->exec("
        SELECT setval(
            pg_get_serial_sequence('users', 'id'),
            COALESCE((SELECT MAX(id) FROM users), 1),
            true
        );
    ");

    $pdo->exec("
        SELECT setval(
            pg_get_serial_sequence('drops', 'id'),
            COALESCE((SELECT MAX(id) FROM drops), 1),
            true
        );
    ");
}

ddrop_init_database($pdo);
ddrop_seed_database($pdo);
