<?php

$host = getenv('DB_HOST') ?: 'db';
$port = getenv('DB_PORT') ?: '5432';
$dbname = getenv('DB_NAME') ?: 'dropshipping_app';
$user = getenv('DB_USER');
$pass = getenv('DB_PASS');

if (!$user || !$pass) {
    die('Database credentials are missing.');
}

try {
    $pdo = new PDO(
        "pgsql:host={$host};port={$port};dbname={$dbname}",
        $user,
        $pass,
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ]
    );
} catch (PDOException $e) {
    die('DB connection failed: ' . $e->getMessage());
}

function ddrop_init_database(PDO $pdo): void
{
    $pdo->exec("DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'drop_status') THEN
            CREATE TYPE drop_status AS ENUM ('upcoming','live','sold_out','ended');
        END IF;
    END$$;");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS drops (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            brand VARCHAR(100) NOT NULL,
            model VARCHAR(150),
            sku VARCHAR(100),
            colorway VARCHAR(150),
            release_date TIMESTAMP NOT NULL,
            retail_price NUMERIC(10,2) NOT NULL,
            currency VARCHAR(10) DEFAULT 'EUR',
            image_url TEXT,
            store_name VARCHAR(100),
            store_link TEXT,
            description TEXT,
            status drop_status DEFAULT 'upcoming',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            ai_summary TEXT
        );
    ");
}

function ddrop_seed_database(PDO $pdo): void
{
    $dropCount = (int)$pdo->query("SELECT COUNT(*) FROM drops")->fetchColumn();

    if ($dropCount > 0) {
        return;
    }

    $stmt = $pdo->prepare("
        INSERT INTO drops (
            id, title, brand, model, sku, colorway, release_date,
            retail_price, currency, image_url, store_name, store_link,
            description, status, created_at, updated_at, ai_summary
        ) VALUES (
            :id, :title, :brand, :model, :sku, :colorway, :release_date,
            :retail_price, :currency, :image_url, :store_name, :store_link,
            :description, :status, :created_at, :updated_at, :ai_summary
        )
        ON CONFLICT (id) DO NOTHING
    ");

    $rows = [
        [
            'id' => 1,
            'title' => 'Nike Dunk Low Panda',
            'brand' => 'Nike',
            'model' => 'Dunk Low',
            'sku' => 'DD1391-100',
            'colorway' => 'Black / White',
            'release_date' => '2026-04-10 09:00:00',
            'retail_price' => 120.00,
            'currency' => 'EUR',
            'image_url' => 'https://static.ftshp.digital/img/p/6/7/4/9/7/1/674971-full_product.jpg',
            'store_name' => 'Nike SNKRS',
            'store_link' => 'https://example.com/drop-link',
            'description' => 'Populární model s vysokou poptávkou.',
            'status' => 'upcoming',
            'created_at' => '2026-03-25 22:40:08',
            'updated_at' => '2026-04-08 22:49:42',
            'ai_summary' => 'AI shrnutí zatím není dostupné v této veřejné verzi projektu.'
        ],
        [
            'id' => 2,
            'title' => 'Air Jordan 1 Retro High OG',
            'brand' => 'Jordan',
            'model' => 'Jordan 1 High',
            'sku' => 'DZ5485-010',
            'colorway' => 'Black / Red',
            'release_date' => '2026-04-14 09:00:00',
            'retail_price' => 190.00,
            'currency' => 'EUR',
            'image_url' => 'https://blob.sxv.pl/shops/media/f1000/2023/nike/221577/air-jordan-1-retro-high-og-dz5485-042-653f88e9c297e.jpg',
            'store_name' => 'Nike SNKRS',
            'store_link' => 'https://example.com/jordan-drop',
            'description' => 'Velmi očekávaný release.',
            'status' => 'upcoming',
            'created_at' => '2026-03-25 22:40:08',
            'updated_at' => '2026-03-25 22:44:28',
            'ai_summary' => 'AI shrnutí zatím není dostupné v této veřejné verzi projektu.'
        ],
    ];

    foreach ($rows as $row) {
        $stmt->execute([
            ':id' => $row['id'],
            ':title' => $row['title'],
            ':brand' => $row['brand'],
            ':model' => $row['model'],
            ':sku' => $row['sku'],
            ':colorway' => $row['colorway'],
            ':release_date' => $row['release_date'],
            ':retail_price' => $row['retail_price'],
            ':currency' => $row['currency'],
            ':image_url' => $row['image_url'],
            ':store_name' => $row['store_name'],
            ':store_link' => $row['store_link'],
            ':description' => $row['description'],
            ':status' => $row['status'],
            ':created_at' => $row['created_at'],
            ':updated_at' => $row['updated_at'],
            ':ai_summary' => $row['ai_summary'],
        ]);
    }
}

ddrop_init_database($pdo);
ddrop_seed_database($pdo);
