<?php

require_once __DIR__ . '/config/db.php';

function tableExists(PDO $pdo, string $tableName): bool
{
    $stmt = $pdo->prepare("
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = :table_name
        )
    ");
    $stmt->execute([':table_name' => $tableName]);
    return (bool) $stmt->fetchColumn();
}

function initializeDatabase(PDO $pdo): void
{
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS drops (
            id INTEGER PRIMARY KEY,
            title VARCHAR(255),
            brand VARCHAR(100),
            model VARCHAR(255),
            sku VARCHAR(100),
            colorway VARCHAR(255),
            release_date TIMESTAMP NULL,
            retail_price NUMERIC(10,2) NULL,
            currency VARCHAR(10) DEFAULT 'EUR',
            store_name VARCHAR(255),
            store_link TEXT,
            description TEXT,
            image_url TEXT,
            ai_summary TEXT,
            status VARCHAR(50) DEFAULT 'upcoming'
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(100) NOT NULL,
            email VARCHAR(255) NOT NULL,
            password_hash TEXT NOT NULL
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS price_watchlist (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            discord_user_id VARCHAR(100),
            product_url TEXT,
            product_title TEXT,
            current_price NUMERIC(10,2) NULL,
            target_price NUMERIC(10,2) NULL,
            currency VARCHAR(10) DEFAULT 'CZK',
            status VARCHAR(50) DEFAULT 'active',
            last_checked_at TIMESTAMP NULL,
            last_notified_price NUMERIC(10,2) NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    ");

    $pdo->exec("
        CREATE TABLE IF NOT EXISTS price_watch_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            watch_id INTEGER,
            checked_price NUMERIC(10,2) NULL,
            in_stock BOOLEAN DEFAULT TRUE,
            checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    ");
}

function syncDropsIfEmpty(PDO $pdo): void
{
    $count = (int) $pdo->query("SELECT COUNT(*) FROM drops")->fetchColumn();
    if ($count > 0) {
        return;
    }

    $apiUrl = 'https://ddrop.net/api/drops.php';
    $json = @file_get_contents($apiUrl);

    if ($json === false) {
        return;
    }

    $data = json_decode($json, true);
    if (!is_array($data)) {
        return;
    }

    $stmt = $pdo->prepare("
        INSERT INTO drops (
            id, title, brand, model, sku, colorway, release_date,
            retail_price, currency, store_name, store_link,
            description, image_url, ai_summary, status
        ) VALUES (
            :id, :title, :brand, :model, :sku, :colorway, :release_date,
            :retail_price, :currency, :store_name, :store_link,
            :description, :image_url, :ai_summary, :status
        )
        ON CONFLICT (id) DO UPDATE SET
            title = EXCLUDED.title,
            brand = EXCLUDED.brand,
            model = EXCLUDED.model,
            sku = EXCLUDED.sku,
            colorway = EXCLUDED.colorway,
            release_date = EXCLUDED.release_date,
            retail_price = EXCLUDED.retail_price,
            currency = EXCLUDED.currency,
            store_name = EXCLUDED.store_name,
            store_link = EXCLUDED.store_link,
            description = EXCLUDED.description,
            image_url = EXCLUDED.image_url,
            ai_summary = EXCLUDED.ai_summary,
            status = EXCLUDED.status
    ");

    foreach ($data as $drop) {
        $stmt->execute([
            ':id' => $drop['id'] ?? null,
            ':title' => $drop['title'] ?? null,
            ':brand' => $drop['brand'] ?? null,
            ':model' => $drop['model'] ?? null,
            ':sku' => $drop['sku'] ?? null,
            ':colorway' => $drop['colorway'] ?? null,
            ':release_date' => $drop['release_date'] ?? null,
            ':retail_price' => $drop['retail_price'] ?? null,
            ':currency' => $drop['currency'] ?? 'EUR',
            ':store_name' => $drop['store_name'] ?? null,
            ':store_link' => $drop['store_link'] ?? null,
            ':description' => $drop['description'] ?? null,
            ':image_url' => $drop['image_url'] ?? null,
            ':ai_summary' => $drop['ai_summary'] ?? null,
            ':status' => $drop['status'] ?? 'upcoming',
        ]);
    }
}

initializeDatabase($pdo);
syncDropsIfEmpty($pdo);
