DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'drop_status'
    ) THEN
        CREATE TYPE drop_status AS ENUM (
            'upcoming',
            'live',
            'sold_out',
            'ended'
        );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS drops (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(150),
    sku VARCHAR(100),
    colorway VARCHAR(150),
    release_date TIMESTAMP NOT NULL,
    retail_price NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'EUR',
    image_url TEXT,
    store_name VARCHAR(100),
    store_link TEXT,
    description TEXT,
    status drop_status DEFAULT 'upcoming',
    ai_summary TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS watchlist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    drop_id INTEGER NOT NULL REFERENCES drops(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, drop_id)
);

CREATE TABLE IF NOT EXISTS ai_generations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drop_id INTEGER NOT NULL REFERENCES drops(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    response TEXT,
    model VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (
    id,
    username,
    email,
    password_hash
) VALUES (
    1,
    'demo_user',
    'demo@example.test',
    '$2y$10$Y8zwZlMvjDpgzWrcgE3g4eb6x8XijXbf1VbzZbT2pGx6g5Y5aS7By'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO drops (
    id,
    title,
    brand,
    model,
    sku,
    colorway,
    release_date,
    retail_price,
    currency,
    image_url,
    store_name,
    store_link,
    description,
    status,
    ai_summary,
    created_at,
    updated_at
) VALUES
(
    1,
    'Nike Dunk Low Panda',
    'Nike',
    'Dunk Low',
    'DD1391-100',
    'Black / White',
    '2026-04-10 09:00:00',
    120.00,
    'EUR',
    'https://static.ftshp.digital/img/p/6/7/4/9/7/1/674971-full_product.jpg',
    'Nike SNKRS',
    'https://example.com/drop-link',
    'Populární model s vysokou poptávkou.',
    'upcoming',
    NULL,
    '2026-03-25 22:40:08',
    '2026-04-08 22:49:42'
),
(
    2,
    'Air Jordan 1 Retro High OG',
    'Jordan',
    'Jordan 1 High',
    'DZ5485-010',
    'Black / Royal Blue',
    '2026-04-14 09:00:00',
    190.00,
    'EUR',
    'https://blob.sxv.pl/shops/media/f1000/2023/nike/221577/air-jordan-1-retro-high-og-dz5485-042-653f88e9c297e.jpg',
    'Nike SNKRS',
    'https://example.com/jordan-drop',
    'Velmi očekávaný release.',
    'upcoming',
    NULL,
    '2026-03-25 22:40:08',
    '2026-03-25 22:44:28'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO watchlist (
    user_id,
    drop_id
) VALUES
(1, 1),
(1, 2)
ON CONFLICT (user_id, drop_id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    COALESCE((SELECT MAX(id) FROM users), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('drops', 'id'),
    COALESCE((SELECT MAX(id) FROM drops), 1),
    true
);
